-- MedCore Hospital Management
-- Sample Data

-- DOCTOR

INSERT INTO DOCTOR VALUES (1, 'Ali', 'Hassan', 'Raza');
INSERT INTO DOCTOR VALUES (2, 'Sara', 'Noor', 'Khan');
INSERT INTO DOCTOR VALUES (3, 'Usman', 'Tariq', 'Malik');

-- DOCTOR SPECIALIZATION

INSERT INTO DOCTOR_SPECIALIZATION VALUES (1, 'Cardiology');
INSERT INTO DOCTOR_SPECIALIZATION VALUES (2, 'Neurology');
INSERT INTO DOCTOR_SPECIALIZATION VALUES (3, 'Orthopedics');

-- DOCTOR QUALIFICATION

INSERT INTO DOCTOR_QUALIFICATION VALUES (1, 'MBBS');
INSERT INTO DOCTOR_QUALIFICATION VALUES (1, 'FCPS');
INSERT INTO DOCTOR_QUALIFICATION VALUES (2, 'MD');

-- PATIENT

INSERT INTO PATIENT VALUES (
    101,
    25,
    TO_DATE('2000-05-12', 'YYYY-MM-DD'),
    'Gulberg',
    'Lahore'
);

INSERT INTO PATIENT VALUES (
    102,
    30,
    TO_DATE('1995-08-20', 'YYYY-MM-DD'),
    'University Town',
    'Peshawar'
);

INSERT INTO PATIENT VALUES (
    103,
    22,
    TO_DATE('2003-02-10', 'YYYY-MM-DD'),
    'DHA',
    'Karachi'
);

-- MEDICINE

INSERT INTO MEDICINE VALUES (501, 1500, 5);
INSERT INTO MEDICINE VALUES (502, 2300, 3);
INSERT INTO MEDICINE VALUES (503, 900, 10);

-- TREATS

INSERT INTO TREATS VALUES (1, 101);
INSERT INTO TREATS VALUES (1, 102);
INSERT INTO TREATS VALUES (2, 103);

-- BILL

INSERT INTO BILL VALUES (101, 501);
INSERT INTO BILL VALUES (101, 502);
INSERT INTO BILL VALUES (102, 503);

COMMIT;
